# Generated by Django 6.0.6 on 2026-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nf',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
