# Generated by Django 6.0.6 on 2026-07-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_manager', '0002_alter_nf_descricao_alter_nf_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nf',
            name='nome',
        ),
        migrations.AddField(
            model_name='nf',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nf',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='nf',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nf',
            name='cnpj',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='nf',
            name='complemento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nf',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nf',
            name='inscricao_estadual',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nf',
            name='inscricao_municipal',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nf',
            name='logradouro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nf',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='nf',
            name='numero_contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nf',
            name='op',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='nf',
            name='pessoa_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nf',
            name='razao_social',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nf',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='nf',
            name='servico',
            field=models.CharField(default='', max_length=100),
        ),
    ]
