# Generated by Django 6.0.6 on 2026-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_manager', '0003_remove_nf_nome_nf_bairro_nf_cep_nf_cidade_nf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='cep',
            field=models.CharField(default='', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='cnpj',
            field=models.CharField(default='', max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='complemento',
            field=models.CharField(default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contato'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='inscricao_estadual',
            field=models.CharField(default='', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='inscricao_municipal',
            field=models.CharField(default='', max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='logradouro',
            field=models.CharField(default='', max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='numero',
            field=models.CharField(default='', max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='numero_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Contato'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='op',
            field=models.CharField(default='', max_length=4, verbose_name='Ordem de Produção (OP)'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='pessoa_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='razao_social',
            field=models.CharField(default='', max_length=100, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='servico',
            field=models.CharField(default='', max_length=100, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('emitido', 'Emitido')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='uf',
            field=models.CharField(default='RJ', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
    ]
