# Generated by Django 6.0.6 on 2026-07-04 22:59

import nf_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_manager', '0004_alter_nf_bairro_alter_nf_cep_alter_nf_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=8, null=True, validators=[nf_manager.models.validate_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='cnpj',
            field=models.CharField(default='', max_length=14, validators=[nf_manager.models.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[nf_manager.models.validate_email], verbose_name='Email de Contato'),
        ),
        migrations.AlterField(
            model_name='nf',
            name='numero_contato',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[nf_manager.models.validate_phone], verbose_name='Número de Contato'),
        ),
    ]
