# Generated by Django 6.0.6 on 2026-07-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_manager', '0005_alter_nf_cep_alter_nf_cnpj_alter_nf_email_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nf',
            name='codigo_verificacao',
            field=models.CharField(default='', max_length=20, verbose_name='Código de Verificação'),
        ),
        migrations.AddField(
            model_name='nf',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='nf',
            name='numero_nfse',
            field=models.CharField(default='', max_length=20, verbose_name='Número da NFSe'),
        ),
    ]
